#!/bin/bash

STLINK=/home/james/tools/stlink/st-util
EJTAGPROXY=/home/james/project/ejtagproxy/ejtagproxy
EGDBSERVER=/opt/adapteva/esdk/tools/host/x86_64/bin/e-server

CORTEXM0_GDB=/home/james/arm_cortex-m0_toolchain/bin/arm-none-eabi-gdb
CORTEXA8_GDB=/home/james/arm_cortex-a8_toolchain/bin/arm-none-eabi-gdb
FRAMEWORK=/home/james/university/summer12/lowpower-framework-git

c=`screen -ls | grep framework | wc -l`

if [ "$c" != "0" ]; then
    screen -r framework -X quit
fi


screen -S framework -d -m bash

if [[ $@ == *cortex-m0* ]]; then
    echo Starting STLINK
    screen -r framework -X screen bash -i -c "while true; do  $STLINK -p 4200 -v0 -c 0x0bb11477; done"
    sleep 1
    echo Starting gdbhost for cortex-m0
    screen -r framework -X screen bash -i -c "$CORTEXM0_GDB -x $FRAMEWORK/gdbhost_cortex-m0.py"
    sleep 1
fi
if [[ $@ == .*cortex-a8.* ]]; then
    echo Starting STLINK for cortex-m3
    screen -r framework -X screen bash -i -c "while true; do  $STLINK -1 -p 4201 -v0; done"
    sleep 1
    echo Starting gdbhost for cortex-m3
    screen -r framework -X screen bash -i -c "$GDB_FILES/arm-none-eabi-gdb -x $FRAMEWORK/gdbhost_cortex-m3.py"
    sleep 1
fi

echo Starting energy server
screen -r framework -X screen python $FRAMEWORK/comms/energy_server.py -v
sleep 1

for dev in /dev/ttyUSB*
do
    c=`udevadm info --name=$dev --query=all | grep cp210x | wc -l`
    if [ "$c" == "1" ]; then
        echo Starting UART server
        screen -r framework -X screen python $FRAMEWORK/comms/uart_server_parallel.py $dev
        sleep 1
        break
    fi
done


echo Starting XC-1A energy monitor
screen -r framework -X screen sudo -u xc1_user bash -i -c "source /home/xc1_user/.bashrc && xrun --io $FRAMEWORK/board_controller/power/app_power/bin/app_power.xe"

if [[ $@ == *cortex-a8* ]]; then
    active=`screen -ls | grep a8 | wc -l`
    if [ "$active" == "0" ]; then
        screen -S a8 -d -m bash
        echo Starting OpenOCD for cortex-a8
        screen -r a8 -X screen bash -i -c "openocd -f board/ti_beaglebone.cfg"
        sleep 1

        echo Starting gdbhost for cortex-a8
        screen -r a8 -X screen bash -i -c "$CORTEXA8_GDB -x $FRAMEWORK/gdbhost_cortex-a8.py"
        sleep 1
    else
        echo Cortex-A8 already active
    fi
fi

echo Started
